    [profile.default]
    src = 'contracts'
    out = 'anza/src/artifacts'
    libs = ["node_modules", "lib"]
    remappings = [
        '@optionality.io/=node_modules/@optionality.io/',
        'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    ]
    solc = "0.8.17"
    gas_reports = ["LoanContract", "LoanTreasurey", "CollateralVault", "AnzaDebtStorefront"]
    [fuzz]
    runs = 300
    
    
    # See more config options https://github.com/foundry-rs/foundry/tree/master/config