[profile.default]
src = 'contracts'
out = 'anza/src/artifacts'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@optionality.io/=node_modules/@optionality.io/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config